from enum import Enum


class Namespace(str, Enum):
    """Namespaces for experimental KG."""

    DATABASE_CROSS_REFERENCE = "dbxref"
    SYNONYM = "synonym"


class EdgeLabel(str, Enum):
    """Labels for experimental KG edges."""

    IS_A = "IS_A"
    HAS_DATABASE_CROSS_REFERENCE = "HAS_DATABASE_CROSS_REFERENCE"
    HAS_SYNONYM = "HAS_SYNONYM"
    SUBJECT_OF = "SUBJECT_OF"
    HAS_OBJECT = "HAS_OBJECT"
    DERIVED_FROM = "DERIVED_FROM"
    INDICATES = "INDICATES"
    HAS_MECHANISM_OF_ACTION = "HAS_MECHANISM_OF_ACTION"
    HAS_TARGET = "HAS_TARGET"
    HAS_DRUG_WARNING = "HAS_DRUG_WARNING"
    HAS_ADVERSE_REACTION = "HAS_ADVERSE_REACTION"
    ASSOCIATED_WITH = "ASSOCIATED_WITH"
    HAS_INTERACTION = "HAS_INTERACTION"
    MENTIONS = "MENTIONS"
    SUPPORTED_BY = "SUPPORTED_BY"
    IS_PART_OF = "IS_PART_OF"
    HAS_HOMOLOGUE_IN_SPECIES = "HAS_HOMOLOGUE_IN_SPECIES"
    LOCATED_IN = "LOCATED_IN"
    BELONGS_TO = "BELONGS_TO"
    RELATED_TO = "RELATED_TO"
    INVOLVES_IN = "INVOLVES_IN"
    MODELLED_BY = "MODELLED_BY"
    ALLELE_IN = "ALLELE_IN"
    HAS_PHENOTYPE = "HAS_PHENOTYPE"
    CLASSIFIED_AS = "CLASSIFIED_AS"
